version: "3.9"


services:
  postgres:
    container_name: postgres-spring-boot-IMS
    image: postgres:latest
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: liz
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5352:5432"
    networks:
      - backend
    restart: unless-stopped


  redis:
    image: redis:7
    container_name: redis-ims
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped

  backend:
    image: charlize367/inventory_backend:latest
    container_name: inventory-backend-container

    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory
      SPRING_DATASOURCE_USERNAME: liz
      SPRING_DATASOURCE_PASSWORD: password
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  pgdata: